import type { Metadata } from "next";
import React from "react";
import Hamburger from "@/components/hamburger";
import "./globals.css";

export const metadata: Metadata = {
  title: "SPARK: Reigniting Learning and Innovation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <><header>
      <Hamburger />
    </header><>
        <html lang="en">

          <body>
            {children}
          </body>
        </html> </></>
  );
}