import type { Metadata } from "next";
import React from "react";
import Hamburger from "@/components/hamburger";
import "./globals.css";

export const metadata: Metadata = {
  title: "SPARK: Reigniting Learning and Innovation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <body>
        <Hamburger />
        {children}
      </body>
    </html>
  );
}